# Project

# Final Project - Analyzing Sales Data

**Date**: 21 August 2022

**Author**: Waranchana Ratiruetayawong (Cher)

**Course**: `Pandas Foundation`

In [26]:
# import data
import pandas as pd
df = pd.read_csv("sample-store.csv")

In [27]:
# preview top 5 rows
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2019-152156,11/8/2019,11/11/2019,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2019-152156,11/8/2019,11/11/2019,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2019-138688,6/12/2019,6/16/2019,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2018-108966,10/11/2018,10/18/2018,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2018-108966,10/11/2018,10/18/2018,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [28]:
# shape of dataframe
df.shape

(9994, 21)

In [29]:
# see data frame information using .info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          9994 non-null   int64
 1   Order ID        9994 non-null   object
 2   Order Date      9994 non-null   object
 3   Ship Date       9994 non-null   object
 4   Ship Mode       9994 non-null   object
 5   Customer ID     9994 non-null   object
 6   Customer Name   9994 non-null   object
 7   Segment         9994 non-null   object
 8   Country/Region  9994 non-null   object
 9   City            9994 non-null   object
 10  State           9994 non-null   object
 11  Postal Code     9983 non-null   float64
 12  Region          9994 non-null   object
 13  Product ID      9994 non-null   object
 14  Category        9994 non-null   object
 15  Sub-Category    9994 non-null   object
 16  Product Name    9994 non-null   object
 17  Sales           9994 non-null   float64
 18  Quantity        9994 non-null   int64
 19  Discount        9994 non-null   float64
 20  Profit          9994 non-null   float64
dtypes: float64(4), int64(2), object(15)
memory usage: 1.6+ MB

In [30]:
#Clean column name
    #Since the columns headers contain space and dash that can be difficult to type in later.  
    #It is better to change the column headers to be all lower case without space and dash.

#1.Create list of columns in dataframe
df_col = list(df.columns)

#2.Make all character lower case and remove space and dash using list comprehension
clean_col = [title.lower().replace(" ", "").replace("-", "") for title in df_col]

#3.Apply #2 list as new headers
df.columns = clean_col

df.head()

,rowid,orderid,orderdate,shipdate,shipmode,customerid,customername,segment,country/region,city,...,postalcode,region,productid,category,subcategory,productname,sales,quantity,discount,profit
0,1,CA-2019-152156,11/8/2019,11/11/2019,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2019-152156,11/8/2019,11/11/2019,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2019-138688,6/12/2019,6/16/2019,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2018-108966,10/11/2018,10/18/2018,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2018-108966,10/11/2018,10/18/2018,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [31]:
# TODO - convert order date and ship date to datetime in the original dataframe

#Use pd.to_datetime() function and apply to the same column
df['orderdate'] = pd.to_datetime(df['orderdate']).dt.date
df['shipdate'] = pd.to_datetime(df['shipdate']).dt.date

df

,rowid,orderid,orderdate,shipdate,shipmode,customerid,customername,segment,country/region,city,...,postalcode,region,productid,category,subcategory,productname,sales,quantity,discount,profit
0,1,CA-2019-152156,2019-11-08,2019-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2019-152156,2019-11-08,2019-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2019-138688,2019-06-12,2019-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2018-108966,2018-10-11,2018-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2018-108966,2018-10-11,2018-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2017-110422,2017-01-21,2017-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180.0,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2020-121258,2020-02-26,2020-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2020-121258,2020-02-26,2020-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2020-121258,2020-02-26,2020-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2020-119914,2020-05-04,2020-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [32]:
# TODO - count nan in postal code column

#1.Use df['postalcode']isna() function to detect missing values in postal code column
#2.Use sum() function to sum missing values
df['postalcode'].isna().sum()

11

In [33]:
# TODO - filter rows with missing values

#1.Check missing values in dataframe
var = df.columns[df.isna().any()]
    #result: Index(['postalcode'], dtype='object') 
        #It means column 'postalcode' has missing values

#2 filter rows with condition that column 'postalcode' has missing values
df[df['postalcode'].isna()]

,rowid,orderid,orderdate,shipdate,shipmode,customerid,customername,segment,country/region,city,...,postalcode,region,productid,category,subcategory,productname,sales,quantity,discount,profit
2234,2235,CA-2020-104066,2020-12-05,2020-12-10,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,...,NaN,East,TEC-AC-10001013,Technology,Accessories,Logitech ClearChat Comfort/USB Headset H390,205.03,7,0.0,67.6599
5274,5275,CA-2018-162887,2018-11-07,2018-11-09,Second Class,SV-20785,Stewart Visinsky,Consumer,United States,Burlington,...,NaN,East,FUR-CH-10000595,Furniture,Chairs,Safco Contoured Stacking Chairs,715.20,3,0.0,178.8000
8798,8799,US-2019-150140,2019-04-06,2019-04-10,Standard Class,VM-21685,Valerie Mitchum,Home Office,United States,Burlington,...,NaN,East,TEC-PH-10002555,Technology,Phones,Nortel Meridian M5316 Digital phone,1294.75,5,0.0,336.6350
9146,9147,US-2019-165505,2019-01-23,2019-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,...,NaN,East,TEC-AC-10002926,Technology,Accessories,Logitech Wireless Marathon Mouse M705,99.98,2,0.0,42.9914
9147,9148,US-2019-165505,2019-01-23,2019-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,...,NaN,East,OFF-AR-10003477,Office Supplies,Art,4009 Highlighters,8.04,6,0.0,2.7336
9148,9149,US-2019-165505,2019-01-23,2019-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,...,NaN,East,OFF-ST-10001526,Office Supplies,Storage,Iceberg Mobile Mega Data/Printer Cart,1564.29,13,0.0,406.7154
9386,9387,US-2020-127292,2020-01-19,2020-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,...,NaN,East,OFF-PA-10000157,Office Supplies,Paper,Xerox 191,79.92,4,0.0,37.5624
9387,9388,US-2020-127292,2020-01-19,2020-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,...,NaN,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,12.28,1,0.0,5.7716
9388,9389,US-2020-127292,2020-01-19,2020-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,...,NaN,East,OFF-AP-10000828,Office Supplies,Appliances,Avanti 4.4 Cu. Ft. Refrigerator,542.94,3,0.0,152.0232
9389,9390,US-2020-127292,2020-01-19,2020-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,...,NaN,East,OFF-EN-10001509,Office Supplies,Envelopes,Poly String Tie Envelopes,2.04,1,0.0,0.9588
9741,9742,CA-2018-117086,2018-11-08,2018-11-12,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,...,NaN,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.90,5,0.0,1013.1270

In [34]:
# TODO - Explore this dataset on your owns, ask your own questions

#top10 royalty customers by the most number of order 

#1.Group dataframe by segment and count values in customerid column by using agg({"customerid":'value_counts'}) function
    #**try to use df.groupby('segment')['customerid'].value_counts() but nothing has shown**
#2. rename agg columns to 'count' by adding [('count', 'value_counts')] in agg function
#3. reset index
df2 = df.groupby('segment').agg({"customerid": [('count', 'value_counts')]}).reset_index()

#4. show only the first 10 customers using .head(10)
df2.head(10)

## Data Analysis Part

Answer 10 below questions to get credit from this course. Write `pandas` code to find answers.

In [11]:
# TODO 01 - how many columns, rows in this dataset
df.shape

(9994, 21)

In [12]:
# TODO 02 - is there any missing values?, if there is, which colunm? how many nan values?

#1.Check missing values in dataframe and assign variable in na
na = df.isna().sum()

#2. filter row with condition na > 0 : means filter column that has missing value > 0
na[na > 0]

#result: column postalcode has 11 missing values

In [13]:
# TODO 03 - your friend ask for `California` data, filter it and export csv for him

#Filter rows with condition that column 'state' exact contains California
ca = df[df['state'] == 'California']

#Use to_csv() function to write .csv file name sample_store_california.csv
ca.to_csv('sample_store_california.csv')

ca.head()

,rowid,orderid,orderdate,shipdate,shipmode,customerid,customername,segment,country/region,city,...,postalcode,region,productid,category,subcategory,productname,sales,quantity,discount,profit
2,3,CA-2019-138688,2019-06-12,2019-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
5,6,CA-2017-115812,2017-06-09,2017-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
6,7,CA-2017-115812,2017-06-09,2017-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656
7,8,CA-2017-115812,2017-06-09,2017-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152,6,0.2,90.7152
8,9,CA-2017-115812,2017-06-09,2017-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,0.2,5.7825

In [14]:
# TODO 04 - your friend ask for all order data in `California` and `Texas` in 2017 (look at Order Date), send him csv file

#Filter row with..
    #1st condition: state is California or state is Taxas -> using | symbol as OR operator
    #2nd condition: orders that took place in year 2017
        #use .dt.year to filter only year 
#combine 1st condition and 2nd condition with & symbol
ca_tx_2017 = df[((df['state'] == 'California') | (df['state'] == 'Texas')) & (df['orderdate'].dt.year == 2017)] 

#Use to_csv() function to write .csv file name sample_store_california-texas_2017.csv
ca_tx_2017.to_csv('sample_store_california-texas_2017.csv')

ca_tx_2017.head()

,rowid,orderid,orderdate,shipdate,shipmode,customerid,customername,segment,country/region,city,...,postalcode,region,productid,category,subcategory,productname,sales,quantity,discount,profit
5,6,CA-2017-115812,2017-06-09,2017-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
6,7,CA-2017-115812,2017-06-09,2017-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656
7,8,CA-2017-115812,2017-06-09,2017-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152,6,0.2,90.7152
8,9,CA-2017-115812,2017-06-09,2017-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,0.2,5.7825
9,10,CA-2017-115812,2017-06-09,2017-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.900,5,0.0,34.4700

In [15]:
# TODO 05 - how much total sales, average sales, and standard deviation of sales your company make in 2017

#1.Create new dataframe that filter year only in 2017 name df2017
df2017 = df[df['orderdate'].dt.year == 2017]

#2.Use .agg() function to apply more than one aggregate function at once
df2017['sales'].agg(['sum', 'mean', 'std'])

In [16]:
 # TODO 06 - which Segment has the highest profit in 2018

#1.Create new dataframe that filter year only in 2018 name df2018
df2018 = df[df['orderdate'].dt.year == 2018]

#2.Sum profit column in df2018 and group by segment column
#3.Reset index and sort column by descending order -> from highest to lowest profit
#4.Use head(1) function to get only the first row
df2018.groupby('segment')['profit'].sum().reset_index()\
    .sort_values('profit', ascending=False).head(1)

,segment,profit
0,Consumer,28460.1665

In [17]:
# TODO 07 - which top 5 States have the least total sales between 15 April 2019 - 31 December 2019

#1.Create new dataframe that filter orderdate between 15 April 2019 - 31 December 2019 name sales1
sales1 = df[(df['orderdate'] >= '2019-4-15') & (df['orderdate'] <= '2019-12-31')]

#2.Sum sales column in sales1 and group by state column
#3.Reset index and sort sales column from lowest to highest (default:ascending order)
#4.Use head(5) function to show only first 5 rows
sales1.groupby('state')['sales'].sum().reset_index().sort_values('sales').head(5)

,state,sales
26,New Hampshire,49.05
28,New Mexico,64.08
7,District of Columbia,117.07
16,Louisiana,249.80
36,South Carolina,502.48

In [18]:
# TODO 08 - what is the proportion of total sales (%) in West + Central in 2019 e.g. 25% 

#1.Create new dataframe that filter year only in 2019 name df2019
df2019 = df[df['orderdate'].dt.year == 2019]

#2.Filter row in df2019 that region is in west or central using .query() function
    #then assign filtered dataframe to wc_2019
wc_2019 = df2019.query("region == 'West' | region == 'Central'")

#3.Get total sales of df2019 and wc_2019 -> df2019['sales'].sum() and wc_2019['sales'].sum()
total_sales_2019 = df2019['sales'].sum()
total_sales_wc_2019 = wc_2019['sales'].sum()

#4.Find proportion 
prop = (total_sales_wc_2019 / total_sales_2019)*100

#5.Print result with 2 digit decimal using .round(decimals=2)
print(prop.round(decimals=2),'%')

# q25 = sales2019['sales'].quantile(0.25)
# q50 = sales2019['sales'].quantile(0.5)
# q75 = sales2019['sales'].quantile(0.75)

# print(q25,q50, q75, sep='\n')

54.97 %

In [19]:

# TODO 09 - find top 10 popular products in terms of number of orders vs. total sales during 2019-2020

#1.Create new dataframe that filtered in 2019-2020 name df2019_2020
df_2019_2020 = df[(df['orderdate'].dt.year == 2019) | (df['orderdate'].dt.year == 2020)]

#2.Find total order of all product in 2019-2020  : count only order not quantity
#   2.1 Count values productname column in df_2019_2020 
#   2.2 Sort values in descending order and reset index
#   2.3 Assign results to new variable name total_pdsales_2019_2020
total_pdorder_2019_2020 = df_2019_2020['productname'].value_counts().sort_values(ascending=False).reset_index()
#   2.4 Change columns name from index(old) to productname(new) and from productname(old) to order(new)
total_pdorder_2019_2020 = total_pdorder_2019_2020.rename(columns = {'index':'productname', 'productname':'order'})

#3.Find total sales of all product in 2019-2020 
#   3.1 Sum sales column in df_2019_2020 and group by productname column
#   3.2 Sort values in descending order and reset index
#   3.3 Assign results to new variable name total_pdsales_2019_2020
total_pdsales_2019_2020 = df_2019_2020.groupby('productname')['sales'].sum().sort_values(ascending=False).reset_index()

#4.Concat 2 dataframes use pd.concat() function : axis=1 is to concatenating along the columns
#   4.1 .head(10) to show only the first 10 rows
top10_product = pd.concat([total_pdorder_2019_2020, total_pdsales_2019_2020],axis=1).head(10)

top10_product

,productname,order,productname,sales
0,Easy-staple paper,27,Canon imageCLASS 2200 Advanced Copier,61599.824
1,Staples,24,Hewlett Packard LaserJet 3310 Copier,16079.732
2,Staple envelope,22,"3D Systems Cube Printer, 2nd Generation, Magenta",14299.890
3,Staples in misc. colors,13,GBC Ibimaster 500 Manual ProClick Binding System,13621.542
4,Chromcraft Round Conference Tables,12,GBC DocuBind TL300 Electric Binding System,12737.258
5,Storex Dura Pro Binders,12,GBC DocuBind P400 Electric Binding System,12521.108
6,Staple remover,12,Samsung Galaxy Mega 6.3,12263.708
7,"Global Wood Trimmed Manager's Task Chair, Khaki",11,HON 5400 Series Task Chairs for Big and Tall,11846.562
8,Avery Non-Stick Binders,11,Martin Yale Chadless Opener Electric Letter Op...,11825.902
9,Sterilite Officeware Hinged File Box,10,Global Troy Executive Leather Low-Back Tilter,10169.894

In [20]:
# TODO 10 - plot at least 2 plots, any plot you think interesting :)

#Top 5 state with highest sales
df.groupby('state')['sales'].sum()\
    .sort_values(ascending=False).head(5)\
    .plot.bar(color=['coral','salmon','pink', 'peachpuff','moccasin'])

In [21]:

#Profit over the years

#1.Sum profit group by year in orderdate column
total_profit_years = df.groupby(df['orderdate'].dt.year)['profit'].sum().reset_index()

#2.Change column name from orderdate(old) to year(new)
total_profit_years = total_profit_years.rename(columns = {'orderdate':'year'})

#3.convert datatype in year column from int64 to string
total_profit_years['year'] = total_profit_years['year'].astype('str')
    #If don't convert to string the year axis in plot will have a decimal

#4. plot line graph : x axis = year column and y axis = profit column
total_profit_years.plot.line(x='year', y='profit')

In [22]:
# TODO Bonus - use np.where() to create new column in dataframe to help you answer your own questions

#Which row has minus profit

#1.Create new column name profit? 
#   1.1 use np.where to filter which rows in profit column has value more than 0, then put True to profit? column.
#       for rows that have value less than 0  put False to profit? column.
import numpy as np
df['profit?'] = np.where(df['profit'] > 0 , True, False)

#2.Filter rows in profit? column with False
#   2.1 name filtered dataframe as df_loss
df_loss = df[df['profit?'] == False]

df_loss

#Example of other usage

#Which subcategory has the most loss (count rows)
#df_loss['subcategory'].value_counts(ascending=False)

,rowid,orderid,orderdate,shipdate,shipmode,customerid,customername,segment,country/region,city,...,region,productid,category,subcategory,productname,sales,quantity,discount,profit,profit?
3,4,US-2018-108966,2018-10-11,2018-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,False
14,15,US-2018-118983,2018-11-22,2018-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100,5,0.80,-123.8580,False
15,16,US-2018-118983,2018-11-22,2018-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,Central,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.5440,3,0.80,-3.8160,False
23,24,US-2020-156909,2020-07-16,2020-07-18,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,...,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.3720,2,0.30,-1.0196,False
27,28,US-2018-150630,2018-09-17,2018-09-21,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7,0.50,-1665.0522,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9921,9922,CA-2017-111360,2017-11-24,2017-11-30,Standard Class,AT-10435,Alyssa Tate,Home Office,United States,Akron,...,East,OFF-BI-10003350,Office Supplies,Binders,Acco Expandable Hanging Binders,5.7420,3,0.70,-4.5936,False
9931,9932,CA-2018-104948,2018-11-13,2018-11-17,Standard Class,KH-16510,Keith Herrera,Consumer,United States,San Bernardino,...,West,FUR-BO-10004357,Furniture,Bookcases,O'Sullivan Living Dimensions 3-Shelf Bookcases,683.3320,4,0.15,-40.1960,False
9937,9938,CA-2019-164889,2019-06-03,2019-06-06,Second Class,CP-12340,Christine Phan,Corporate,United States,Los Angeles,...,West,FUR-TA-10001676,Furniture,Tables,Hon 61000 Series Interactive Training Tables,71.0880,2,0.20,-1.7772,False
9962,9963,CA-2018-168088,2018-03-19,2018-03-22,First Class,CM-12655,Corinna Mitchell,Home Office,United States,Houston,...,Central,FUR-BO-10004218,Furniture,Bookcases,Bush Heritage Pine Collection 5-Shelf Bookcase...,383.4656,4,0.32,-67.6704,False
9977,9978,US-2019-103674,2019-12-06,2019-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,West,OFF-FA-10003467,Office Supplies,Fasteners,"Alliance Big Bands Rubber Bands, 12/Pack",13.8600,7,0.00,0.0000,False